title: Jekyll-theme-rawposts
SEOTitle: Jekyll-theme-rawposts | rawposts Jekyll 主题
logo: '/assets/logo.png' 
label: BLOG # this name will be displayed on the title name of homepage
author: David Dong
email: dqdongg@hotmail.com
description: "This is a free jekyll portfolio-style theme. To be simple, light & clean! "
keywords: "Jekyll Theme, 主题 rawpost"
show_excerpts: true # set to true to show excerpts on the homepage
url: 'https://dejjon.netlify.app'
baseurl: ''
repository: github.com/Juan-Jones/jekyll-theme-rawposts
cdn_baseurl: https://cdn.jsdelivr.net/gh/gangdong/gangdong.github.io@dev
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
# Pagination 
paginate: 10
paginate_path: "/blog/page:num/"
rawposts:
  name: Rawpost Theme
  tagline: Your awesome words
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  highlighter: rouge
  syntax: monokai.sublime  # stylesheet, 
                           # options: base16, base16.dark, base16.light, base16.monokai, 
                           # base16.monokai.dark, base16.monokai.light, base16.solarized, base16.solarized.dark, base16.solarized.light, 
                           # bw, colorful, github, gruvbox, gruvbox.dark, gruvbox.light, igorpro, magritte, molokai, monokai, monokai.sublime, 
                           # pastie, thankful_eyes, tulip
 # markdown: kramdown
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  condensed_mobile:
    #- home
    - page
    - post
    - extension
    
  reading_time: true  # set to true to add reading time statistics
  archives: true  # set to true to generate archives page 
  categories: true  # set to true to generate categories page
  related_posts: true #  set to true to enable related posts
  gittalk: true  # set to true to add gittalk 
  navigation: true    # set to to add page navigation bar
  show_statistics: true  #set to true to show statistics of site visitors number
  rss: true  #set to true to add rss 
  source_code: true  #set to true to add link to source code
  analytics_id: G-3MXGF3F8QN  #use Google analytics
  share_media: true  # generate social share links in footer
  show_category_box: true    # display post categories box in the index page
  social_links:
    wechat: 
    github:  gangdong
    linkedIn: daviddong
    mail: daviddong
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# BUILD SETTINGS
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'codehilite'
    # span:
    #   line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: pretty
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-seo-tag, jekyll-toc, jekyll-tagging-related_posts, jekyll/tagging, jekyll-feed, jemoji, jekyll-seo-tag]
exclude: [".jekyll-cache", "Gemfile", "README.md"]
github: [metadata]
# if you want the blog to be below the home page through a link  - comment out the following line and then remove the hashes from the next 2 lines. In other words you want to include the blog/index and exclude the index on the home page.
exclude: ["blog/index.html"]
# paginate_path: "blog/page:num"
# exclude: ["index.html"]

# Note you will then want to add the blog to the menubar through the CMS
# You should also UNCOMMENT the homepageitems section in the config.yml file inside the the admin folder

#emoji:
  # The emoji's image host url, 'https://github.githubassets.com' (default).
  # The trailing can't end with '/', and it's can be setting to '' (empty string).
  #src: 'https://github.githubassets.com'
  
  # The emoji's image path of above host url, '/images/icons/' (default).
  # If it must start with '/' character, and it's can not be a empty string.
  #path: '/images/icons/'
